In [1]:
import pandas as pd 
import numpy as np

In [2]:
movies = pd.read_csv('/Users/samreenasiddiqui/Desktop/cinematch_recommender/data/data_1m/movies.dat', sep='::', engine='python', encoding='latin-1',
    names=['movie_id', 'title', 'genres'])

movies.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [3]:
ratings = pd.read_csv('/Users/samreenasiddiqui/Desktop/cinematch_recommender/data/data_1m/ratings.dat', sep='::',engine='python', encoding='latin-1',
                      names = ["user_id","movie_id","rating","timestamp"])
ratings['timestamp'] = pd.to_datetime(ratings['timestamp'],unit='s')

ratings.head()

   user_id  movie_id  rating           timestamp
0        1      1193       5 2000-12-31 22:12:40
1        1       661       3 2000-12-31 22:35:09
2        1       914       3 2000-12-31 22:32:48
3        1      3408       4 2000-12-31 22:04:35
4        1      2355       5 2001-01-06 23:38:11

In [4]:
users = pd.read_csv('/Users/samreenasiddiqui/Desktop/cinematch_recommender/data/data_1m/users.dat', sep='::', engine='python', encoding='latin-1',
             names = ["user_id","gender","age","occupation","zip-code"]        )

users.head()

   user_id gender  age  occupation zip-code
0        1      F    1          10    48067
1        2      M   56          16    70072
2        3      M   25          15    55117
3        4      M   45           7    02460
4        5      M   25          20    55455

In [5]:
len(users)

6040

In [6]:
len(movies)

3883

In [7]:
len(ratings)

1000209

In [8]:
avg_amt_ratings = ratings.groupby("user_id")['rating'].agg(['count', 'mean']).reset_index()
avg_amt_ratings

      user_id  count      mean
0           1     53  4.188679
1           2    129  3.713178
2           3     51  3.901961
3           4     21  4.190476
4           5    198  3.146465
...       ...    ...       ...
6035     6036    888  3.302928
6036     6037    202  3.717822
6037     6038     20  3.800000
6038     6039    123  3.878049
6039     6040    341  3.577713

[6040 rows x 3 columns]

In [9]:
avg_amt_ratings.sort_values(by = 'count', ascending = False)

      user_id  count      mean
4168     4169   2314  3.551858
1679     1680   1850  3.555676
4276     4277   1743  4.134825
1940     1941   1595  3.054545
1180     1181   1521  2.815911
...       ...    ...       ...
5724     5725     20  3.450000
3406     3407     20  3.500000
1663     1664     20  3.400000
4418     4419     20  3.300000
3020     3021     20  3.250000

[6040 rows x 3 columns]

In [10]:
avg_movie_rantings = ratings.groupby("movie_id")['rating'].agg(['count', 'mean']).reset_index()
avg_movie_rantings.sort_values(by = 'count', ascending = False)

      movie_id  count      mean
2651      2858   3428  4.317386
253        260   2991  4.453694
1106      1196   2990  4.292977
1120      1210   2883  4.022893
466        480   2672  3.763847
...        ...    ...       ...
3013      3237      1  1.000000
725        763      1  3.000000
607        624      1  4.000000
2367      2563      1  3.000000
3064      3290      1  3.000000

[3706 rows x 3 columns]

In [11]:
full_table = ratings.merge(right = movies , on = ['movie_id'], how = 'left')
full_table = full_table.merge(right = users, on = ['user_id'], how = 'left')
full_table[['user_id','gender','age', 'occupation','zip-code','movie_id','title','genres', 'rating','timestamp']]
full_table

,user_id,movie_id,rating,timestamp,title,genres,gender,age,occupation,zip-code
0,1,1193,5,2000-12-31 22:12:40,One Flew Over the Cuckoo's Nest (1975),Drama,F,1,10,48067
1,1,661,3,2000-12-31 22:35:09,James and the Giant Peach (1996),Animation|Children's|Musical,F,1,10,48067
2,1,914,3,2000-12-31 22:32:48,My Fair Lady (1964),Musical|Romance,F,1,10,48067
3,1,3408,4,2000-12-31 22:04:35,Erin Brockovich (2000),Drama,F,1,10,48067
4,1,2355,5,2001-01-06 23:38:11,"Bug's Life, A (1998)",Animation|Children's|Comedy,F,1,10,48067
...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,2000-04-26 02:35:41,Weekend at Bernie's (1989),Comedy,M,25,6,11106
1000205,6040,1094,5,2000-04-25 23:21:27,"Crying Game, The (1992)",Drama|Romance|War,M,25,6,11106
1000206,6040,562,5,2000-04-25 23:19:06,Welcome to the Dollhouse (1995),Comedy|Drama,M,25,6,11106
1000207,6040,1096,4,2000-04-26 02:20:48,Sophie's Choice (1982),Drama,M,25,6,11106
1000208,6040,1097,4,2000-04-26 02:19:29,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,M,25,6,11106

In [12]:
full_table['rating'].describe()

count    1.000209e+06
mean     3.581564e+00
std      1.117102e+00
min      1.000000e+00
25%      3.000000e+00
50%      4.000000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [13]:
full_table.groupby('genres')['rating'].describe().sort_values(by='mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
genres,,,,,,,,
Animation|Comedy|Thriller,688.0,4.473837,0.739339,1.0,4.0,5.0,5.00,5.0
Sci-Fi|War,1367.0,4.449890,0.805507,1.0,4.0,5.0,5.00,5.0
Animation,459.0,4.394336,0.819555,1.0,4.0,5.0,5.00,5.0
Film-Noir|Mystery,1584.0,4.367424,0.776372,1.0,4.0,5.0,5.00,5.0
Adventure|War,1644.0,4.346107,0.794099,1.0,4.0,5.0,5.00,5.0
...,...,...,...,...,...,...,...,...
Action|Adventure|Children's|Fantasy,44.0,2.090909,1.074399,1.0,1.0,2.0,3.00,5.0
Comedy|Film-Noir|Thriller,5.0,2.000000,1.000000,1.0,1.0,2.0,3.00,3.0
Action|Adventure|Children's|Sci-Fi,350.0,1.874286,1.044111,1.0,1.0,2.0,2.00,5.0
Action|Children's,295.0,1.742373,0.926592,1.0,1.0,1.0,2.00,4.0
Action|Adventure|Children's,44.0,1.318182,0.638775,1.0,1.0,1.0,1.25,4.0

In [14]:
full_table['relevant'] = full_table['rating'] >= 4
full_table

,user_id,movie_id,rating,timestamp,title,genres,gender,age,occupation,zip-code,relevant
0,1,1193,5,2000-12-31 22:12:40,One Flew Over the Cuckoo's Nest (1975),Drama,F,1,10,48067,True
1,1,661,3,2000-12-31 22:35:09,James and the Giant Peach (1996),Animation|Children's|Musical,F,1,10,48067,False
2,1,914,3,2000-12-31 22:32:48,My Fair Lady (1964),Musical|Romance,F,1,10,48067,False
3,1,3408,4,2000-12-31 22:04:35,Erin Brockovich (2000),Drama,F,1,10,48067,True
4,1,2355,5,2001-01-06 23:38:11,"Bug's Life, A (1998)",Animation|Children's|Comedy,F,1,10,48067,True
...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,2000-04-26 02:35:41,Weekend at Bernie's (1989),Comedy,M,25,6,11106,False
1000205,6040,1094,5,2000-04-25 23:21:27,"Crying Game, The (1992)",Drama|Romance|War,M,25,6,11106,True
1000206,6040,562,5,2000-04-25 23:19:06,Welcome to the Dollhouse (1995),Comedy|Drama,M,25,6,11106,True
1000207,6040,1096,4,2000-04-26 02:20:48,Sophie's Choice (1982),Drama,M,25,6,11106,True
1000208,6040,1097,4,2000-04-26 02:19:29,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,M,25,6,11106,True

In [15]:
p_relevant = sum(full_table['relevant'])/ len(full_table)

In [16]:
full_table.groupby('user_id')['relevant'].mean().sort_values().reset_index()

      user_id  relevant
0        4486  0.000000
1        3598  0.000000
2        5850  0.017241
3        2744  0.072464
4        4349  0.074074
...       ...       ...
6035      447  1.000000
6036      283  1.000000
6037     4755  1.000000
6038     2543  1.000000
6039     3287  1.000000

[6040 rows x 2 columns]

In [17]:
full_table.groupby('movie_id')['relevant'].mean().sort_values().reset_index()

      movie_id  relevant
0         2576       0.0
1          847       0.0
2          843       0.0
3         2592       0.0
4         3458       0.0
...        ...       ...
3701      1316       1.0
3702      2480       1.0
3703      3353       1.0
3704       439       1.0
3705      3229       1.0

[3706 rows x 2 columns]

# Split and General Popularity Ranking

In [21]:
import sys 
sys.path.append("..")
from src.split import chron_train_val_test
train, val, test= chron_train_val_test(full_table)

In [23]:
popular_movies = full_table.groupby("movie_id").size().sort_values(ascending = False)
popular_movies.head(10)

movie_id
2858    3428
260     2991
1196    2990
1210    2883
480     2672
2028    2653
589     2649
2571    2590
1270    2583
593     2578
dtype: int64

In [ ]:
#general recommendations 

user_id = 1
seen_movies = set(train[train['user_id'] == user_id]['movie_id'])

reccomended_movies = [movie for movie in popular_movies.index if movie not in seen_movies][:10] #top popular movies they haven't seen (train = past)
reccomended_movies

movies[movies["movie_id"].isin(reccomended_movies)][['movie_id','title']]

relevant_test_movies = set(test.loc[(test['user_id'] == user_id) & (test['relevant']), "movie_id"]) #movies they saw in the future 
relevant_test_movies

hits = set(reccomended_movies) & set(relevant_test_movies) #how many "recomended" movies did they end up seeing 
hits

precision_at_10 = len(hits)/10
precision_at_10
recall_at_10 = len(hits)/len(relevant_test_movies)
recall_at_10

0.0